cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'

brew 'awscli'
brew 'cmake'
brew 'docker'
brew 'docker-compose'
brew 'fzf'
brew 'ghq'
brew 'git'
brew 'go'
brew 'gradle'
brew 'htop'
brew 'llvm'
brew 'neovim'
brew 'nvm'
brew 'protobuf'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'rbenv'
brew 'rustup-init'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'wget'
brew 'zsh'

cask 'firefox'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'google-cloud-sdk'
cask 'google-japanese-ime'
cask 'java'
cask 'iterm2'
cask 'kindle'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'visual-studio-code-insiders'
