cask_args appdir: '/Applications', require_sha: true

brew 'eza'
brew 'fd'
brew 'fish'
brew 'fzf'
brew 'gh'
brew 'ghq'
brew 'git'
brew 'goenv'
brew 'gpg'
brew 'lazygit'
brew 'lefthook'
brew 'neovim'
brew 'node-build'
brew 'nodenv'
brew 'pinentry-mac'
brew 'ripgrep'
brew 'starship'
brew 'stow'
brew 'tig'
brew 'tree-sitter'
brew 'wget'
brew 'zoxide'

cask '1password'
cask '1password-cli'
cask 'claude'
cask 'claude-code'
cask 'font-hack-nerd-font'
cask 'ghostty'
cask 'github'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-japanese-ime'
cask 'karabiner-elements'
cask 'raycast'
cask 'visual-studio-code'
