cask_args appdir: '/Applications', require_sha: true

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/core'

brew 'docker-compose'
brew 'exa'
brew 'fish'
brew 'fzf'
brew 'ghq'
brew 'git'
brew 'gpg'
brew 'neovim'
brew 'node-build'
brew 'nodenv'
brew 'pinentry-mac'
brew 'pyenv'
brew 'rbenv'
brew 'terraform'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'wget'

cask 'brave-browser'
cask 'docker'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-japanese-ime'
cask 'iterm2'
cask 'visual-studio-code'
