# ==============================================================================
# tmux全体の設定
#
# 以下のように省略できるが、省略せずに統一する
# set => set-option
# setw => set-window-option
# ==============================================================================

## 基本設定
if-shell "test -f ~/.tmux/base.tmux" "source-file ~/.tmux/base.tmux"

## タイトルの設定
if-shell "test -f ~/.tmux/title.tmux" "source-file ~/.tmux/title.tmux"

## ステータスラインの設定
if-shell "test -f ~/.tmux/statusline.tmux" "source-file ~/.tmux/statusline.tmux"

## メッセージの設定
if-shell "test -f ~/.tmux/message.tmux" "source-file ~/.tmux/message.tmux"

## メッセージの設定
if-shell "test -f ~/.tmux/window.tmux" "source-file ~/.tmux/window.tmux"

## キーバインドの設定
if-shell "test -f ~/.tmux/keybind.tmux" "source-file ~/.tmux/keybind.tmux"

## tmuxプラグインの設定
if-shell "test -f ~/.tmux/plugins.tmux" "source-file ~/.tmux/plugins.tmux"
