#!/usr/bin/env bash

DOTFILES_ROOT=$(cd "$(dirname "$0")/.." && pwd -P)

set -e

CONFIG_DIR=~/.config
if [ -d $CONFIG_DIR ]; then
  rm -rf $CONFIG_DIR
fi

mkdir $CONFIG_DIR

ln -vsf $DOTFILES_ROOT/.config/fish          $CONFIG_DIR/fish
ln -vsf $DOTFILES_ROOT/.config/ghostty       $CONFIG_DIR/ghostty
ln -vsf $DOTFILES_ROOT/.config/git           $CONFIG_DIR/git
ln -vsf $DOTFILES_ROOT/.config/karabiner     $CONFIG_DIR/karabiner
ln -vsf $DOTFILES_ROOT/.config/nvim          $CONFIG_DIR/nvim
ln -vsf $DOTFILES_ROOT/.config/tmux          $CONFIG_DIR/tmux
ln -vsf $DOTFILES_ROOT/.config/starship.toml $CONFIG_DIR/starship.toml

echo -e 'All installed!'
